Better error messages

diff --git a/.github/workflows/go-format.yml b/.github/workflows/go-format.yml
--- a/.github/workflows/go-format.yml
+++ b/.github/workflows/go-format.yml
@@ -5,6 +5,17 @@ jobs:
     name: Golang Formatter
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@main
+    - name: Checkout
+      uses: actions/checkout@main
+
+    - name: Set up Go
+      uses: actions/setup-go@v5
+      with:
+        go-version: '1.21'
+
     - name: Golang Formatting
-      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
+      run: |
+        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
+          echo "Error: Golang files need to be formatted. Run `gofmt -s -w .`."
+          exit 1
+        fi
diff --git a/.github/workflows/templ-generate.yml b/.github/workflows/templ-generate.yml
--- a/.github/workflows/templ-generate.yml
+++ b/.github/workflows/templ-generate.yml
@@ -20,4 +20,8 @@ jobs:
       run: templ generate
 
     - name: Check for changes
-      run: if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then exit 1; fi
+      run: |
+        if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
+          echo "Error: Templ files need to be updated. Run `templ generate`."
+          exit 1
+        fi
